// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Command$Web from "../Interop/Command.bs.js";
import WindowCss from "./Window.css";
import * as Titlebar$Web from "../Titlebar/Titlebar.bs.js";

function onMinimize(param) {
  return Command$Web.send(/* MinimizeWindow */1);
}

function onMaximize(param) {
  
}

function onClose(param) {
  return Command$Web.send(/* CloseWindow */0);
}

function $$Window(Props) {
  var children = Props.children;
  var titleOpt = Props.title;
  var minimizeOpt = Props.minimize;
  var maximizeOpt = Props.maximize;
  var closeOpt = Props.close;
  var titlebarOpt = Props.titlebar;
  var title = titleOpt !== undefined ? titleOpt : "";
  var minimize = minimizeOpt !== undefined ? minimizeOpt : true;
  var maximize = maximizeOpt !== undefined ? maximizeOpt : true;
  var close = closeOpt !== undefined ? closeOpt : true;
  var titlebar = titlebarOpt !== undefined ? titlebarOpt : true;
  return React.createElement("div", {
              className: "window"
            }, titlebar ? React.createElement(Titlebar$Web.make, {
                    title: title,
                    minimize: minimize,
                    maximize: maximize,
                    close: close,
                    onMinimize: onMinimize,
                    onMaximize: onMaximize,
                    onClose: onClose
                  }) : React.createElement(React.Fragment, undefined), React.createElement("div", {
                  className: "window__content " + (
                    titlebar ? "" : "window__content--no-titlebar"
                  )
                }, children));
}

var make = $$Window;

export {
  make ,
  
}
/*  Not a pure module */
