// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import WindowCss from "./Window.css";
import * as Titlebar$Web from "../Titlebar/Titlebar.bs.js";
import * as WebCommand$Web from "../Interop/WebCommand.bs.js";

function onMinimize(param) {
  return WebCommand$Web.sendCommand(/* MinimizeWindow */1);
}

function onMaximize(param) {
  
}

function onClose(param) {
  return WebCommand$Web.sendCommand(/* CloseWindow */0);
}

function $$Window(Props) {
  var title = Props.title;
  var children = Props.children;
  var minimizeOpt = Props.minimize;
  var maximizeOpt = Props.maximize;
  var closeOpt = Props.close;
  var minimize = minimizeOpt !== undefined ? minimizeOpt : true;
  var maximize = maximizeOpt !== undefined ? maximizeOpt : true;
  var close = closeOpt !== undefined ? closeOpt : true;
  return React.createElement("div", {
              className: "window"
            }, React.createElement(Titlebar$Web.make, {
                  title: title,
                  minimize: minimize,
                  maximize: maximize,
                  close: close,
                  onMinimize: onMinimize,
                  onMaximize: onMaximize,
                  onClose: onClose
                }), React.createElement("div", {
                  className: "window__content"
                }, children));
}

var make = $$Window;

export {
  make ,
  
}
/*  Not a pure module */
