// Generated by ReScript, PLEASE EDIT WITH CARE


var Activity = {};

var Airplay = {};

var AlertCircle = {};

var AlertOctagon = {};

var AlertTriangle = {};

var AlignCenter = {};

var AlignJustify = {};

var AlignLeft = {};

var AlignRight = {};

var Anchor = {};

var Aperture = {};

var Archive = {};

var ArrowDown = {};

var ArrowDownCircle = {};

var ArrowDownLeft = {};

var ArrowDownRight = {};

var ArrowLeft = {};

var ArrowLeftCircle = {};

var ArrowRight = {};

var ArrowRightCircle = {};

var ArrowUp = {};

var ArrowUpCircle = {};

var ArrowUpLeft = {};

var ArrowUpRight = {};

var AtSign = {};

var Award = {};

var BarChart = {};

var BarChart2 = {};

var Battery = {};

var BatteryCharging = {};

var Bell = {};

var BellOff = {};

var Bluetooth = {};

var Bold = {};

var Book = {};

var BookOpen = {};

var Bookmark = {};

var Box = {};

var Briefcase = {};

var Calendar = {};

var Camera = {};

var CameraOff = {};

var Cast = {};

var Check = {};

var CheckCircle = {};

var CheckSquare = {};

var ChevronDown = {};

var ChevronLeft = {};

var ChevronRight = {};

var ChevronUp = {};

var ChevronsDown = {};

var ChevronsLeft = {};

var ChevronsRight = {};

var ChevronsUp = {};

var Chrome = {};

var Circle = {};

var Clipboard = {};

var Clock = {};

var Cloud = {};

var CloudDrizzle = {};

var CloudLightning = {};

var CloudOff = {};

var CloudRain = {};

var CloudSnow = {};

var Code = {};

var Codepen = {};

var Codesandbox = {};

var Coffee = {};

var Columns = {};

var Command = {};

var Compass = {};

var Copy = {};

var CornerDownLeft = {};

var CornerDownRight = {};

var CornerLeftDown = {};

var CornerLeftUp = {};

var CornerRightDown = {};

var CornerRightUp = {};

var CornerUpLeft = {};

var CornerUpRight = {};

var Cpu = {};

var CreditCard = {};

var Crop = {};

var Crosshair = {};

var Database = {};

var Delete = {};

var Disc = {};

var Divide = {};

var DivideCircle = {};

var DivideSquare = {};

var DollarSign = {};

var Download = {};

var DownloadCloud = {};

var Dribbble = {};

var Droplet = {};

var Edit = {};

var Edit2 = {};

var Edit3 = {};

var ExternalLink = {};

var Eye = {};

var EyeOff = {};

var Facebook = {};

var FastForward = {};

var Feather = {};

var Figma = {};

var $$File = {};

var FileMinus = {};

var FilePlus = {};

var FileText = {};

var Film = {};

var Filter = {};

var Flag = {};

var Folder = {};

var FolderMinus = {};

var FolderPlus = {};

var Framer = {};

var Frown = {};

var Gift = {};

var GitBranch = {};

var GitCommit = {};

var GitHub = {};

var GitMerge = {};

var GitPullRequest = {};

var Gitlab = {};

var Globe = {};

var Grid = {};

var HardDrive = {};

var Hash = {};

var Headphones = {};

var Heart = {};

var HelpCircle = {};

var Hexagon = {};

var Home = {};

var $$Image = {};

var Inbox = {};

var Info = {};

var Instagram = {};

var Italic = {};

var Key = {};

var Layers = {};

var Layout = {};

var LifeBuoy = {};

var Link = {};

var Link2 = {};

var Linkedin = {};

var List = {};

var Loader = {};

var Lock = {};

var LogIn = {};

var LogOut = {};

var Mail = {};

var $$Map = {};

var MapPin = {};

var Maximize = {};

var Maximize2 = {};

var Meh = {};

var Menu = {};

var MessageCircle = {};

var MessageSquare = {};

var Mic = {};

var MicOff = {};

var Minimize = {};

var Minimize2 = {};

var Minus = {};

var MinusCircle = {};

var MinusSquare = {};

var Monitor = {};

var Moon = {};

var MoreHorizontal = {};

var MoreVertical = {};

var MousePointer = {};

var Move = {};

var Music = {};

var Navigation = {};

var Navigation2 = {};

var Octagon = {};

var Package = {};

var Paperclip = {};

var Pause = {};

var PauseCircle = {};

var PenTool = {};

var Percent = {};

var Phone = {};

var PhoneCall = {};

var PhoneForwarded = {};

var PhoneIncoming = {};

var PhoneMissed = {};

var PhoneOff = {};

var PhoneOutgoing = {};

var PieChart = {};

var Play = {};

var PlayCircle = {};

var Plus = {};

var PlusCircle = {};

var PlusSquare = {};

var Pocket = {};

var Power = {};

var Printer = {};

var Radio = {};

var RefreshCcw = {};

var RefreshCw = {};

var Repeat = {};

var Rewind = {};

var RotateCcw = {};

var RotateCw = {};

var Rss = {};

var Save = {};

var Scissors = {};

var Search = {};

var Send = {};

var Server = {};

var Settings = {};

var Share = {};

var Share2 = {};

var Shield = {};

var ShieldOff = {};

var ShoppingBag = {};

var ShoppingCart = {};

var Shuffle = {};

var Sidebar = {};

var SkipBack = {};

var SkipForward = {};

var Slack = {};

var Slash = {};

var Sliders = {};

var Smartphone = {};

var Smile = {};

var Speaker = {};

var Square = {};

var Star = {};

var StopCircle = {};

var Sun = {};

var Sunrise = {};

var Sunset = {};

var Tablet = {};

var Tag = {};

var Target = {};

var Terminal = {};

var Thermometer = {};

var ThumbsDown = {};

var ThumbsUp = {};

var ToggleLeft = {};

var ToggleRight = {};

var Tool = {};

var Trash = {};

var Trash2 = {};

var Trello = {};

var TrendingDown = {};

var TrendingUp = {};

var Triangle = {};

var Truck = {};

var Tv = {};

var Twitch = {};

var Twitter = {};

var Type = {};

var Umbrella = {};

var Underline = {};

var Unlock = {};

var Upload = {};

var UploadCloud = {};

var User = {};

var UserCheck = {};

var UserMinus = {};

var UserPlus = {};

var UserX = {};

var Users = {};

var Video = {};

var VideoOff = {};

var Voicemail = {};

var Volume = {};

var Volume1 = {};

var Volume2 = {};

var VolumeX = {};

var Watch = {};

var Wifi = {};

var WifiOff = {};

var Wind = {};

var X = {};

var XCircle = {};

var XOctagon = {};

var XSquare = {};

var Youtube = {};

var Zap = {};

var ZapOff = {};

var ZoomIn = {};

var ZoomOut = {};

export {
  Activity ,
  Airplay ,
  AlertCircle ,
  AlertOctagon ,
  AlertTriangle ,
  AlignCenter ,
  AlignJustify ,
  AlignLeft ,
  AlignRight ,
  Anchor ,
  Aperture ,
  Archive ,
  ArrowDown ,
  ArrowDownCircle ,
  ArrowDownLeft ,
  ArrowDownRight ,
  ArrowLeft ,
  ArrowLeftCircle ,
  ArrowRight ,
  ArrowRightCircle ,
  ArrowUp ,
  ArrowUpCircle ,
  ArrowUpLeft ,
  ArrowUpRight ,
  AtSign ,
  Award ,
  BarChart ,
  BarChart2 ,
  Battery ,
  BatteryCharging ,
  Bell ,
  BellOff ,
  Bluetooth ,
  Bold ,
  Book ,
  BookOpen ,
  Bookmark ,
  Box ,
  Briefcase ,
  Calendar ,
  Camera ,
  CameraOff ,
  Cast ,
  Check ,
  CheckCircle ,
  CheckSquare ,
  ChevronDown ,
  ChevronLeft ,
  ChevronRight ,
  ChevronUp ,
  ChevronsDown ,
  ChevronsLeft ,
  ChevronsRight ,
  ChevronsUp ,
  Chrome ,
  Circle ,
  Clipboard ,
  Clock ,
  Cloud ,
  CloudDrizzle ,
  CloudLightning ,
  CloudOff ,
  CloudRain ,
  CloudSnow ,
  Code ,
  Codepen ,
  Codesandbox ,
  Coffee ,
  Columns ,
  Command ,
  Compass ,
  Copy ,
  CornerDownLeft ,
  CornerDownRight ,
  CornerLeftDown ,
  CornerLeftUp ,
  CornerRightDown ,
  CornerRightUp ,
  CornerUpLeft ,
  CornerUpRight ,
  Cpu ,
  CreditCard ,
  Crop ,
  Crosshair ,
  Database ,
  Delete ,
  Disc ,
  Divide ,
  DivideCircle ,
  DivideSquare ,
  DollarSign ,
  Download ,
  DownloadCloud ,
  Dribbble ,
  Droplet ,
  Edit ,
  Edit2 ,
  Edit3 ,
  ExternalLink ,
  Eye ,
  EyeOff ,
  Facebook ,
  FastForward ,
  Feather ,
  Figma ,
  $$File ,
  FileMinus ,
  FilePlus ,
  FileText ,
  Film ,
  Filter ,
  Flag ,
  Folder ,
  FolderMinus ,
  FolderPlus ,
  Framer ,
  Frown ,
  Gift ,
  GitBranch ,
  GitCommit ,
  GitHub ,
  GitMerge ,
  GitPullRequest ,
  Gitlab ,
  Globe ,
  Grid ,
  HardDrive ,
  Hash ,
  Headphones ,
  Heart ,
  HelpCircle ,
  Hexagon ,
  Home ,
  $$Image ,
  Inbox ,
  Info ,
  Instagram ,
  Italic ,
  Key ,
  Layers ,
  Layout ,
  LifeBuoy ,
  Link ,
  Link2 ,
  Linkedin ,
  List ,
  Loader ,
  Lock ,
  LogIn ,
  LogOut ,
  Mail ,
  $$Map ,
  MapPin ,
  Maximize ,
  Maximize2 ,
  Meh ,
  Menu ,
  MessageCircle ,
  MessageSquare ,
  Mic ,
  MicOff ,
  Minimize ,
  Minimize2 ,
  Minus ,
  MinusCircle ,
  MinusSquare ,
  Monitor ,
  Moon ,
  MoreHorizontal ,
  MoreVertical ,
  MousePointer ,
  Move ,
  Music ,
  Navigation ,
  Navigation2 ,
  Octagon ,
  Package ,
  Paperclip ,
  Pause ,
  PauseCircle ,
  PenTool ,
  Percent ,
  Phone ,
  PhoneCall ,
  PhoneForwarded ,
  PhoneIncoming ,
  PhoneMissed ,
  PhoneOff ,
  PhoneOutgoing ,
  PieChart ,
  Play ,
  PlayCircle ,
  Plus ,
  PlusCircle ,
  PlusSquare ,
  Pocket ,
  Power ,
  Printer ,
  Radio ,
  RefreshCcw ,
  RefreshCw ,
  Repeat ,
  Rewind ,
  RotateCcw ,
  RotateCw ,
  Rss ,
  Save ,
  Scissors ,
  Search ,
  Send ,
  Server ,
  Settings ,
  Share ,
  Share2 ,
  Shield ,
  ShieldOff ,
  ShoppingBag ,
  ShoppingCart ,
  Shuffle ,
  Sidebar ,
  SkipBack ,
  SkipForward ,
  Slack ,
  Slash ,
  Sliders ,
  Smartphone ,
  Smile ,
  Speaker ,
  Square ,
  Star ,
  StopCircle ,
  Sun ,
  Sunrise ,
  Sunset ,
  Tablet ,
  Tag ,
  Target ,
  Terminal ,
  Thermometer ,
  ThumbsDown ,
  ThumbsUp ,
  ToggleLeft ,
  ToggleRight ,
  Tool ,
  Trash ,
  Trash2 ,
  Trello ,
  TrendingDown ,
  TrendingUp ,
  Triangle ,
  Truck ,
  Tv ,
  Twitch ,
  Twitter ,
  Type ,
  Umbrella ,
  Underline ,
  Unlock ,
  Upload ,
  UploadCloud ,
  User ,
  UserCheck ,
  UserMinus ,
  UserPlus ,
  UserX ,
  Users ,
  Video ,
  VideoOff ,
  Voicemail ,
  Volume ,
  Volume1 ,
  Volume2 ,
  VolumeX ,
  Watch ,
  Wifi ,
  WifiOff ,
  Wind ,
  X ,
  XCircle ,
  XOctagon ,
  XSquare ,
  Youtube ,
  Zap ,
  ZapOff ,
  ZoomIn ,
  ZoomOut ,
  
}
/* No side effect */
