// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Node = require("./Node.bs.js");
var Paths = require("./Paths.bs.js");
var ReactFeather = require("react-feather");

function getIcons(param) {
  return Object.keys(ReactFeather);
}

var makeType = "(~size: int=?) => React.element";

function genIcon(iconName) {
  return ("\r\nmodule " + iconName + " = {\r\n  @module(\"react-feather\") @react.component\r\n  external make: " + makeType + " = \"" + iconName + "\"\r\n}\r\n").trim();
}

function save(code) {
  return $$Node.Fs.writeFileSync(code, Paths.featherIconsPath);
}

function run(param) {
  var icons = Object.keys(ReactFeather);
  var iconsCode = icons.map(genIcon).join("\n\n");
  return $$Node.Fs.writeFileSync("// Do not modify! This file is generated automatically by scripts\n\n" + iconsCode, Paths.featherIconsPath);
}

run(undefined);

exports.getIcons = getIcons;
exports.makeType = makeType;
exports.genIcon = genIcon;
exports.save = save;
exports.run = run;
/*  Not a pure module */
