// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function writeFileSync(content, path) {
  Fs.writeFileSync(path, content);
  
}

var Fs$1 = {
  writeFileSync: writeFileSync
};

var Path = {};

exports.Fs = Fs$1;
exports.Path = Path;
/* fs Not a pure module */
