// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

var projectPath = Path.resolve(__dirname, "..", "..");

var webPath = Path.resolve(projectPath, "web");

var featherIconsPath = Path.resolve(webPath, "src", "FeatherIcon", "FeatherIcon.res");

exports.projectPath = projectPath;
exports.webPath = webPath;
exports.featherIconsPath = featherIconsPath;
/* projectPath Not a pure module */
