// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Window$Web from "../Window/Window.bs.js";
import BreakCss from "./Break.css";
import * as ProgressBar$Web from "../components/ProgressBar.bs.js";

function Break(Props) {
  return React.createElement(Window$Web.make, {
              children: null,
              titlebar: false
            }, React.createElement("div", {
                  className: "break__title"
                }, "Long working sessions may affect your health. Take a break"), React.createElement("div", {
                  className: "break__remaining-slider"
                }, React.createElement(ProgressBar$Web.make, {
                      value: 55.0
                    })), React.createElement("div", {
                  className: "break__remaning-text"
                }, "29 minutes 54 seconds"));
}

var make = Break;

export {
  make ,
  
}
/*  Not a pure module */
