// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Time$Web from "../components/Time.bs.js";
import * as Window$Web from "../Window/Window.bs.js";
import BreakCss from "./Break.css";
import * as Command$Web from "../Interop/Command.bs.js";
import * as Time$Shared from "shared/src/Time.bs.js";
import * as Translate$Web from "../Translate/Translate.bs.js";
import * as ProgressBar$Web from "../components/ProgressBar.bs.js";
import * as Settings$Shared from "shared/src/Settings.bs.js";

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* SetBreakTime */0 :
        return {
                breakTime: action._0,
                tip: state.tip,
                settings: state.settings
              };
    case /* SetSettings */1 :
        return {
                breakTime: state.breakTime,
                tip: state.tip,
                settings: action._0
              };
    case /* SetTip */2 :
        return {
                breakTime: state.breakTime,
                tip: action._0,
                settings: state.settings
              };
    
  }
}

function Break(Props) {
  var match = Translate$Web.useTranslation(undefined);
  var match$1 = React.useReducer(reducer, {
        breakTime: 0,
        tip: 0,
        settings: Settings$Shared.$$default
      });
  var dispatch = match$1[1];
  var state = match$1[0];
  var remainingTime = Time$Shared.millisToTime(state.settings.breakDuration - state.breakTime | 0);
  React.useEffect((function () {
          var listener = Command$Web.on(function (cmd) {
                if (typeof cmd === "number") {
                  return ;
                }
                switch (cmd.TAG | 0) {
                  case /* ReturnSettings */0 :
                      return Curry._1(dispatch, {
                                  TAG: /* SetSettings */1,
                                  _0: cmd._0
                                });
                  case /* ReturnBreakTime */3 :
                      return Curry._1(dispatch, {
                                  TAG: /* SetBreakTime */0,
                                  _0: cmd._0
                                });
                  case /* ReturnTip */4 :
                      return Curry._1(dispatch, {
                                  TAG: /* SetTip */2,
                                  _0: cmd._0
                                });
                  default:
                    return ;
                }
              });
          Command$Web.send(/* GetSettings */2);
          Command$Web.send(/* GetTip */3);
          return (function (param) {
                    return Command$Web.removeListener(listener);
                  });
        }), []);
  return React.createElement(Window$Web.make, {
              children: React.createElement("div", {
                    className: "break"
                  }, React.createElement("div", {
                        className: "break__title"
                      }, Curry._1(match.t, "TIP." + state.tip.toString())), React.createElement("div", {
                        className: "break__remaining"
                      }, React.createElement("div", {
                            className: "break__remaining-progress"
                          }, React.createElement(ProgressBar$Web.make, {
                                max: state.settings.breakDuration,
                                value: state.breakTime
                              })), React.createElement("div", {
                            className: "break__remaining-text"
                          }, React.createElement(Time$Web.make, {
                                minutes: remainingTime.minutes,
                                seconds: remainingTime.seconds
                              })))),
              titlebar: false
            });
}

var make = Break;

export {
  make ,
  
}
/*  Not a pure module */
