// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Electron from "electron";
import * as Utils$Shared from "shared/src/Utils.bs.js";

function getPath(pathName) {
  return Electron.app.getPath(pathName);
}

var App = {
  getPath: getPath
};

var WebContents = {};

function create(frame, webPreferences, width, height, param) {
  return new Electron.BrowserWindow({
              width: width,
              height: height,
              frame: frame,
              webPreferences: webPreferences
            });
}

var BrowserWindow = {
  create: create
};

var Menu = {};

var Tray = {};

function on(channel, listener) {
  Electron.ipcMain.on(channel, Utils$Shared.rest2(listener));
  
}

var IpcMain = {
  on: on
};

export {
  App ,
  WebContents ,
  BrowserWindow ,
  Menu ,
  Tray ,
  IpcMain ,
  
}
/* electron Not a pure module */
