// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Electron from "electron";
import * as Utils$Shared from "shared/src/Utils.bs.js";

function getPath(pathName) {
  return Electron.app.getPath(pathName);
}

var App = {
  getPath: getPath
};

var WebContents = {};

var BrowserWindow = {};

var Menu = {};

var Tray = {};

function on(channel, listener) {
  Electron.ipcMain.on(channel, Utils$Shared.rest2(listener));
  
}

var IpcMain = {
  on: on
};

var Display = {};

var $$Screen = {};

export {
  App ,
  WebContents ,
  BrowserWindow ,
  Menu ,
  Tray ,
  IpcMain ,
  Display ,
  $$Screen ,
  
}
/* electron Not a pure module */
