// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Electron from "electron";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

var App = {};

var WebContents = {};

function create(frame, webPreferences, width, height, param) {
  return new Electron.BrowserWindow({
              width: width,
              height: height,
              frame: frame,
              webPreferences: webPreferences
            });
}

var BrowserWindow = {
  create: create
};

var Menu = {};

var Tray = {};

function on(channel, listener) {
  return Electron.ipcMain.on(channel, (function (param) {
                var args = arguments;
                return Curry._2(listener, Caml_array.get(args, 0), Belt_Array.slice(args, 1, args.length));
              }));
}

var IpcMain = {
  on: on
};

export {
  App ,
  WebContents ,
  BrowserWindow ,
  Menu ,
  Tray ,
  IpcMain ,
  
}
/* electron Not a pure module */
