// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.js";

var Path = {};

function writeFile(data, path) {
  return $$Promise.$$catch(Fs.promises.writeFile(path, data).then(function (param) {
                  return Promise.resolve({
                              TAG: /* Ok */0,
                              _0: undefined
                            });
                }), (function (param) {
                return Promise.resolve({
                            TAG: /* Error */1,
                            _0: /* Unknown */0
                          });
              }));
}

function readFile(path) {
  return $$Promise.$$catch(Fs.promises.readFile(path).then(function (res) {
                  return Promise.resolve({
                              TAG: /* Ok */0,
                              _0: res
                            });
                }), (function (param) {
                return Promise.resolve({
                            TAG: /* Error */1,
                            _0: /* Unknown */0
                          });
              }));
}

var Fs$1 = {
  writeFile: writeFile,
  readFile: readFile
};

export {
  Path ,
  Fs$1 as Fs,
  
}
/* fs Not a pure module */
