// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Break(Props) {
  return React.createElement("div", undefined, "Break");
}

var make = Break;

export {
  make ,
  
}
/* react Not a pure module */
