// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Command$Shared from "shared/src/Command.bs.js";
import * as IpcRenderer$Web from "./IpcRenderer.bs.js";

function on(listener) {
  return IpcRenderer$Web.on("main", (function (param, args) {
                if (args.length !== 1) {
                  return ;
                }
                var cmd = args[0];
                Belt_Option.map(Curry._1(Command$Shared.Serializable.fromString, cmd), listener);
                
              }));
}

function send(command) {
  var parts = Curry._1(Command$Shared.Serializable.toString, command);
  electron.ipcRenderer.send("main", parts);
  
}

function removeListener(param) {
  electron.ipcRenderer.removeListener("main", param);
  
}

export {
  on ,
  send ,
  removeListener ,
  
}
/* Command-Shared Not a pure module */
