// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils$Shared from "shared/src/Utils.bs.js";

function on(channel, listener) {
  var listener$1 = Utils$Shared.rest2(listener);
  electron.ipcRenderer.on(channel, listener$1);
  return listener$1;
}

export {
  on ,
  
}
/* No side effect */
