// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils$Shared from "shared/src/Utils.bs.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function on(channel, listener) {
  electron.ipcRenderer.on(channel, Utils$Shared.rest2(listener));
  
}

function send(channel, args) {
  Caml_splice_call.spliceObjApply(electron.ipcRenderer, "send", [
        channel,
        args
      ]);
  
}

export {
  on ,
  send ,
  
}
/* No side effect */
