// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Command from "../../desktop/Shared/Command.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function on(channel, listener) {
  electron.ipcRenderer.on(channel, (function (param) {
          var args = arguments;
          return Curry._2(listener, Caml_array.get(args, 0), Belt_Array.slice(args, 1, args.length));
        }));
  
}

function onCommand(listener) {
  return on("main", (function (param, args) {
                Belt_Option.map(Command.decodeCommand(args), listener);
                
              }));
}

function sendCommand(command) {
  var parts = Command.encodeCommand(command);
  Caml_splice_call.spliceObjApply(electron.ipcRenderer, "send", [
        "main",
        parts
      ]);
  
}

export {
  on ,
  onCommand ,
  sendCommand ,
  
}
/* No side effect */
