// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Electron from "./Interop/Electron.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Command$Shared from "shared/src/Command.bs.js";

function on(listener) {
  return Electron.IpcMain.on("main", (function ($$event, args) {
                if (args.length !== 1) {
                  return ;
                }
                var cmd = args[0];
                Belt_Option.map(Curry._1(Command$Shared.Serializable.fromString, cmd), (function (cmd) {
                        return Curry._2(listener, $$event, cmd);
                      }));
                
              }));
}

function send(command, webContents) {
  webContents.send("main", Curry._1(Command$Shared.Serializable.toString, command));
  
}

function reply($$event, command) {
  $$event.reply("main", Curry._1(Command$Shared.Serializable.toString, command));
  
}

export {
  on ,
  send ,
  reply ,
  
}
/* Electron Not a pure module */
