// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Node from "./Interop/Node.bs.js";
import * as Path from "path";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Electron from "./Interop/Electron.bs.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function getPath(key) {
  return Path.resolve(Electron.App.getPath("userData"), key + ".json");
}

function set(json, key, stringify) {
  return $$Node.Fs.writeFile(Curry._1(stringify, json), getPath(key));
}

function get(key, parse) {
  return $$Node.Fs.readFile(getPath(key)).then(function (res) {
              return Promise.resolve(Belt_Result.flatMap(res, (function (str) {
                                var obj = Curry._1(parse, str);
                                if (obj !== undefined) {
                                  return {
                                          TAG: /* Ok */0,
                                          _0: Caml_option.valFromOption(obj)
                                        };
                                } else {
                                  return {
                                          TAG: /* Error */1,
                                          _0: /* Unknown */0
                                        };
                                }
                              })));
            });
}

export {
  set ,
  get ,
  
}
/* Node Not a pure module */
