// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Paths from "./Paths.bs.js";
import * as Command from "./Command.bs.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Electron from "./Interop/Electron.bs.js";
import * as Settings from "./Settings.bs.js";
import * as Electron$1 from "electron";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Settings$Shared from "shared/src/Settings.bs.js";
import * as ElectronDevtoolsInstaller from "electron-devtools-installer";
import ElectronDevtoolsInstaller$1 from "electron-devtools-installer";

var appState = {
  tray: undefined,
  settingsWindow: undefined,
  breakWindows: undefined,
  settings: undefined
};

function createWindow(width, height, x, y, startupUrl, param) {
  var $$window = Electron.BrowserWindow.create(width, height, Caml_option.some(x), Caml_option.some(y), false, {
        preload: Path.resolve(Paths.scriptsPath, "windowPreload.js")
      }, undefined);
  var url = Paths.webPath + "#" + startupUrl;
  $$window.loadURL(url);
  if (!Electron$1.app.isPackaged) {
    $$window.webContents.openDevTools();
  }
  return $$window;
}

function loadSettings(param) {
  return Settings.load(undefined).then(function (res) {
              var settings;
              settings = res.TAG === /* Ok */0 ? res._0 : Settings$Shared.$$default;
              appState.settings = settings;
              return Promise.resolve(undefined);
            });
}

function exit(param) {
  Belt_Option.map(appState.settings, (function (settings) {
          return Settings.save(settings).then(function (param) {
                      Electron$1.app.quit();
                      return Promise.resolve(undefined);
                    });
        }));
  
}

function openBreakWindows(param) {
  var match = appState.breakWindows;
  if (match !== undefined) {
    return ;
  } else {
    appState.breakWindows = Electron$1.screen.getAllDisplays().map(function (display) {
          var horizontalPadding = display.bounds.width * 0.1;
          var verticalPadding = display.bounds.height * 0.1;
          return createWindow(display.bounds.width - 2.0 * horizontalPadding | 0, display.bounds.height - 2.0 * verticalPadding | 0, display.bounds.x + horizontalPadding | 0, display.bounds.y + verticalPadding | 0, "break", undefined);
        });
    return ;
  }
}

function openSettingsWindow(param) {
  var match = appState.settingsWindow;
  if (match !== undefined) {
    return ;
  }
  var $$window = createWindow(400, 250, undefined, undefined, "settings", undefined);
  appState.settingsWindow = $$window;
  
}

function createTray(param) {
  var iconPath = Path.resolve(Paths.imgPath, "icon.png");
  var createdTray = new Electron$1.Tray(iconPath);
  appState.tray = Caml_option.some(createdTray);
  var menu = Electron$1.Menu.buildFromTemplate([
        {
          label: "Break",
          click: openBreakWindows
        },
        {
          label: "Settings",
          click: openSettingsWindow
        },
        {
          label: "Exit",
          click: exit
        }
      ]);
  createdTray.setContextMenu(menu);
  
}

function installDevTools(param) {
  if (!Electron$1.app.isPackaged) {
    ElectronDevtoolsInstaller$1(ElectronDevtoolsInstaller.REACT_DEVELOPER_TOOLS);
    return ;
  }
  
}

Command.on(function ($$event, command) {
      var $$window = Electron$1.BrowserWindow.fromWebContents($$event.sender);
      if (typeof command === "number") {
        switch (command) {
          case /* CloseWindow */0 :
              $$window.close();
              Belt_Option.map(appState.settingsWindow, (function (settingsWindow) {
                      if (Caml_obj.caml_equal($$window, settingsWindow)) {
                        appState.settingsWindow = undefined;
                        return ;
                      }
                      
                    }));
              return ;
          case /* MinimizeWindow */1 :
              $$window.minimize();
              return ;
          case /* GetSettings */2 :
              Belt_Option.map(appState.settings, (function (settings) {
                      return Command.send({
                                  TAG: /* ReturnSettings */0,
                                  _0: settings
                                }, $$event.sender);
                    }));
              return ;
          
        }
      } else {
        switch (command.TAG | 0) {
          case /* ReturnSettings */0 :
              return ;
          case /* SetBreakDuration */1 :
              var breakDuration = command._0;
              Belt_Option.map(appState.settings, (function (settings) {
                      appState.settings = {
                        maxBreakInterval: settings.maxBreakInterval,
                        minBreakInterval: settings.minBreakInterval,
                        tickBreakInterval: settings.tickBreakInterval,
                        breakInterval: settings.breakInterval,
                        maxBreakDuration: settings.maxBreakDuration,
                        minBreakDuration: settings.minBreakDuration,
                        tickBreakDuration: settings.tickBreakDuration,
                        breakDuration: breakDuration
                      };
                      
                    }));
              return ;
          case /* SetBreakInterval */2 :
              var breakInterval = command._0;
              Belt_Option.map(appState.settings, (function (settings) {
                      appState.settings = {
                        maxBreakInterval: settings.maxBreakInterval,
                        minBreakInterval: settings.minBreakInterval,
                        tickBreakInterval: settings.tickBreakInterval,
                        breakInterval: breakInterval,
                        maxBreakDuration: settings.maxBreakDuration,
                        minBreakDuration: settings.minBreakDuration,
                        tickBreakDuration: settings.tickBreakDuration,
                        breakDuration: settings.breakDuration
                      };
                      
                    }));
              return ;
          
        }
      }
    });

Electron$1.app.whenReady().then(function (param) {
      installDevTools(undefined);
      return loadSettings(undefined).then(function (param) {
                  createTray(undefined);
                  return Promise.resolve(undefined);
                });
    });

Electron$1.app.on("window-all-closed", (function (prim) {
        
      }));

export {
  appState ,
  createWindow ,
  loadSettings ,
  exit ,
  openBreakWindows ,
  openSettingsWindow ,
  createTray ,
  installDevTools ,
  
}
/*  Not a pure module */
