// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsonStorage from "./JsonStorage.bs.js";

function save(settings) {
  return JsonStorage.set(settings, "settings");
}

function load(param) {
  return JsonStorage.get("settings");
}

export {
  save ,
  load ,
  
}
/* JsonStorage Not a pure module */
