// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsonStorage from "./JsonStorage.bs.js";
import * as Settings$Shared from "shared/src/Settings.bs.js";

function save(settings) {
  return JsonStorage.set(settings, "settings", Settings$Shared.Serializable.toString);
}

function load(param) {
  return JsonStorage.get("settings", Settings$Shared.Serializable.fromString);
}

export {
  save ,
  load ,
  
}
/* JsonStorage Not a pure module */
