// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Settings$Shared from "shared/src/Settings.bs.js";

function save(settings) {
  return Promise.resolve({
              TAG: /* Ok */0,
              _0: undefined
            });
}

function load(param) {
  return Promise.resolve({
              TAG: /* Ok */0,
              _0: Settings$Shared.$$default
            });
}

export {
  save ,
  load ,
  
}
/* Settings-Shared Not a pure module */
