// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import AppCss from "./App.css";
import * as Break$Web from "../Break/Break.bs.js";
import * as Settings$Web from "../Settings/Settings.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.hash;
  switch (match) {
    case "break" :
        return React.createElement(Break$Web.make, {});
    case "settings" :
        return React.createElement(Settings$Web.make, {});
    default:
      return React.createElement("div", undefined, "Page not found");
  }
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
