// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Slider$Web from "../components/Slider.bs.js";
import * as Window$Web from "../Window/Window.bs.js";
import SettingsCss from "./Settings.css";

function Settings(Props) {
  return React.createElement(Window$Web.make, {
              title: "Settings",
              children: React.createElement("div", {
                    className: "settings"
                  }, "Settings", React.createElement(Slider$Web.make, {}), React.createElement(Slider$Web.make, {})),
              maximize: false
            });
}

var make = Settings;

export {
  make ,
  
}
/*  Not a pure module */
