// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Slider$Web from "../components/Slider.bs.js";
import * as Window$Web from "../Window/Window.bs.js";
import SettingsCss from "./Settings.css";

function Settings(Props) {
  return React.createElement(Window$Web.make, {
              title: "Settings",
              children: React.createElement("div", {
                    className: "settings"
                  }, React.createElement("section", {
                        className: "settings__section"
                      }, React.createElement("h3", undefined, "Break interval"), React.createElement("div", {
                            className: "settings__slider"
                          }, React.createElement(Slider$Web.make, {})), React.createElement("p", {
                            className: "settings__detail"
                          }, "2 hours 30 minutes")), React.createElement("section", {
                        className: "settings__section"
                      }, React.createElement("h3", undefined, "Break duration"), React.createElement("div", {
                            className: "settings__slider"
                          }, React.createElement(Slider$Web.make, {})), React.createElement("p", {
                            className: "settings__detail"
                          }, "30 minutes"))),
              maximize: false
            });
}

var make = Settings;

export {
  make ,
  
}
/*  Not a pure module */
