// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

var themes = ["dark"];

var theme = Caml_array.get(themes, 0);

function Theme(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "theme-" + theme
            }, children);
}

var make = Theme;

export {
  make ,
  
}
/* react Not a pure module */
