// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Language$Shared from "./Language.bs.js";

function decodeCommand(args) {
  var len = args.length;
  if (len >= 3) {
    return ;
  }
  switch (len) {
    case 0 :
        return ;
    case 1 :
        var match = args[0];
        switch (match) {
          case "CloseWindow" :
              return /* CloseWindow */0;
          case "GetSettings" :
              return /* GetSettings */2;
          case "MinimizeWindow" :
              return /* MinimizeWindow */1;
          default:
            return ;
        }
    case 2 :
        var match$1 = args[0];
        switch (match$1) {
          case "ChangeLanguage" :
              var payload = args[1];
              return Belt_Option.map(Language$Shared.fromString(payload), (function (language) {
                            return {
                                    TAG: /* ChangeLanguage */4,
                                    _0: language
                                  };
                          }));
          case "LanguageChanged" :
              var payload$1 = args[1];
              return Belt_Option.map(Language$Shared.fromString(payload$1), (function (language) {
                            return {
                                    TAG: /* LanguageChanged */5,
                                    _0: language
                                  };
                          }));
          case "ReturnBreakTime" :
              var payload$2 = args[1];
              return {
                      TAG: /* ReturnBreakTime */3,
                      _0: JSON.parse(payload$2)
                    };
          case "ReturnSettings" :
              var payload$3 = args[1];
              return {
                      TAG: /* ReturnSettings */0,
                      _0: JSON.parse(payload$3)
                    };
          case "SetBreakDuration" :
              var payload$4 = args[1];
              return {
                      TAG: /* SetBreakDuration */1,
                      _0: JSON.parse(payload$4)
                    };
          case "SetBreakInterval" :
              var payload$5 = args[1];
              return {
                      TAG: /* SetBreakInterval */2,
                      _0: JSON.parse(payload$5)
                    };
          default:
            return ;
        }
    
  }
}

function encodeCommand(command) {
  if (typeof command === "number") {
    switch (command) {
      case /* CloseWindow */0 :
          return ["CloseWindow"];
      case /* MinimizeWindow */1 :
          return ["MinimizeWindow"];
      case /* GetSettings */2 :
          return ["GetSettings"];
      
    }
  } else {
    switch (command.TAG | 0) {
      case /* ReturnSettings */0 :
          return [
                  "ReturnSettings",
                  JSON.stringify(command._0)
                ];
      case /* SetBreakDuration */1 :
          return [
                  "SetBreakDuration",
                  JSON.stringify(command._0)
                ];
      case /* SetBreakInterval */2 :
          return [
                  "SetBreakInterval",
                  JSON.stringify(command._0)
                ];
      case /* ReturnBreakTime */3 :
          return [
                  "ReturnBreakTime",
                  JSON.stringify(command._0)
                ];
      case /* ChangeLanguage */4 :
          return [
                  "ChangeLanguage",
                  Language$Shared.toString(command._0)
                ];
      case /* LanguageChanged */5 :
          return [
                  "LanguageChanged",
                  Language$Shared.toString(command._0)
                ];
      
    }
  }
}

export {
  decodeCommand ,
  encodeCommand ,
  
}
/* No side effect */
