// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jzon from "rescript-jzon/src/Jzon.bs.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";

var supportedLanguages = [
  /* En */1,
  /* Ru */0
];

var $$default = Jzon.custom((function (language) {
        return Jzon.encodeWith(language ? "en" : "ru", Jzon.string);
      }), (function (languageStr) {
        return Belt_Result.flatMap(Jzon.decodeWith(languageStr, Jzon.string), (function (language) {
                      switch (language) {
                        case "en" :
                            return {
                                    TAG: /* Ok */0,
                                    _0: /* En */1
                                  };
                        case "ru" :
                            return {
                                    TAG: /* Ok */0,
                                    _0: /* Ru */0
                                  };
                        default:
                          return {
                                  TAG: /* Error */1,
                                  _0: {
                                    NAME: "SyntaxError",
                                    VAL: "Invalid language " + language
                                  }
                                };
                      }
                    }));
      }));

var Codec = {
  $$default: $$default
};

function toString(language) {
  if (language) {
    return "en";
  } else {
    return "ru";
  }
}

function fromString(languageStr) {
  switch (languageStr) {
    case "en" :
        return /* En */1;
    case "ru" :
        return /* Ru */0;
    default:
      console.log(languageStr + " is invalid language");
      return ;
  }
}

var Serializable = {
  toString: toString,
  fromString: fromString
};

export {
  supportedLanguages ,
  Codec ,
  Serializable ,
  
}
/* default Not a pure module */
