// Generated by ReScript, PLEASE EDIT WITH CARE


var supportedLanguages = [
  /* En */1,
  /* Ru */0
];

function toString(language) {
  if (language) {
    return "en";
  } else {
    return "ru";
  }
}

function fromString(language) {
  switch (language) {
    case "en" :
        return /* En */1;
    case "ru" :
        return /* Ru */0;
    default:
      return ;
  }
}

export {
  supportedLanguages ,
  toString ,
  fromString ,
  
}
/* No side effect */
