// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils$Shared from "./Utils.bs.js";

function MakePropsUtils(Item) {
  var merge = Utils$Shared.mergeObjects;
  return {
          merge: merge
        };
}

export {
  MakePropsUtils ,
  
}
/* No side effect */
