// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jzon from "rescript-jzon/src/Jzon.bs.js";
import * as Utils$Shared from "./Utils.bs.js";

function MakeSerializable(Item) {
  var toString = function (item) {
    return Jzon.encodeStringWith(item, Item.$$default);
  };
  var fromString = function (itemStr) {
    return Utils$Shared.resultToOption(Jzon.decodeStringWith(itemStr, Item.$$default));
  };
  return {
          toString: toString,
          fromString: fromString
        };
}

export {
  MakeSerializable ,
  
}
/* No side effect */
