// Generated by ReScript, PLEASE EDIT WITH CARE


var $$default = {
  maxBreakInterval: 10,
  minBreakInterval: 0,
  breakInterval: 0,
  maxBreakDuration: 10,
  minBreakDuration: 0,
  breakDuration: 0
};

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
