// Generated by ReScript, PLEASE EDIT WITH CARE


var defaultSettings = {
  maxBreakInterval: 0,
  minBreakInterval: 0,
  breakInterval: 0,
  maxBreakDuration: 0,
  minBreakDuration: 0,
  breakDuration: 0
};

export {
  defaultSettings ,
  
}
/* No side effect */
