// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Time$Shared from "./Time.bs.js";

var default_maxBreakInterval = Time$Shared.hoursToMillis(2.5);

var default_minBreakInterval = Time$Shared.hoursToMillis(0.5);

var default_tickBreakInterval = Time$Shared.minutesToMillis(5);

var default_breakInterval = Time$Shared.hoursToMillis(1.0);

var default_maxBreakDuration = Time$Shared.minutesToMillis(30);

var default_minBreakDuration = Time$Shared.minutesToMillis(5);

var default_tickBreakDuration = Time$Shared.minutesToMillis(1);

var default_breakDuration = Time$Shared.minutesToMillis(5);

var $$default = {
  maxBreakInterval: default_maxBreakInterval,
  minBreakInterval: default_minBreakInterval,
  tickBreakInterval: default_tickBreakInterval,
  breakInterval: default_breakInterval,
  maxBreakDuration: default_maxBreakDuration,
  minBreakDuration: default_minBreakDuration,
  tickBreakDuration: default_tickBreakDuration,
  breakDuration: default_breakDuration,
  selectedLanguage: /* En */1
};

export {
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
