// Generated by ReScript, PLEASE EDIT WITH CARE


function hoursToMillis(hours) {
  return hours * 3600000 | 0;
}

function minutesToMillis(minutes) {
  return Math.imul(minutes, 60000);
}

function millisToTime(millis) {
  var seconds = millis / 1000 | 0;
  var minutes = seconds / 60 | 0;
  var seconds$1 = seconds - Math.imul(minutes, 60) | 0;
  var hours = minutes / 60 | 0;
  var minutes$1 = minutes - Math.imul(hours, 60) | 0;
  return {
          seconds: seconds$1,
          minutes: minutes$1,
          hours: hours
        };
}

export {
  hoursToMillis ,
  minutesToMillis ,
  millisToTime ,
  
}
/* No side effect */
