// Generated by ReScript, PLEASE EDIT WITH CARE


function hoursToMillis(hours) {
  return hours * 3600000 | 0;
}

function minutesToMillis(minutes) {
  return Math.imul(minutes, 60000);
}

function msToString(ms) {
  var seconds = ms / 1000 | 0;
  var minutes = seconds / 60 | 0;
  var hours = minutes / 60 | 0;
  var minutes$1 = minutes - Math.imul(hours, 60) | 0;
  var minutesStr = "" + minutes$1 + " minute" + (
    minutes$1 > 1 ? "s" : ""
  );
  var hoursStr = "" + hours + " hour" + (
    hours > 1 ? "s" : ""
  );
  if (hours === 0 && minutes$1 === 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "Time.res",
            19,
            14
          ],
          Error: new Error()
        };
  }
  if (minutes$1 !== 0) {
    if (hours !== 0) {
      return hoursStr + " " + minutesStr;
    } else {
      return minutesStr;
    }
  } else {
    return hoursStr;
  }
}

export {
  hoursToMillis ,
  minutesToMillis ,
  msToString ,
  
}
/* No side effect */
