// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Slider from "../components/Slider.bs.js";
import * as $$Window from "../Window/Window.bs.js";
import SettingsCss from "./Settings.css";

function Settings(Props) {
  return React.createElement($$Window.make, {
              title: "Settings",
              children: React.createElement("div", {
                    className: "settings"
                  }, "Settings", React.createElement(Slider.make, {}), React.createElement(Slider.make, {})),
              maximize: false
            });
}

var make = Settings;

export {
  make ,
  
}
/*  Not a pure module */
