// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Command$Web from "../Interop/Command.bs.js";
import * as Translate$Web from "../Translate/Translate.bs.js";
import * as Language$Shared from "shared/src/Language.bs.js";
import LanguageSelectorCss from "./LanguageSelector.css";

function LanguageSelector(Props) {
  var match = Translate$Web.useTranslation(undefined);
  var i18n = match.i18n;
  var t1 = match.t1;
  return React.createElement("div", {
              className: "language-selector"
            }, Language$Shared.supportedLanguages.map(function (language) {
                  var languageStr = Language$Shared.toString(language);
                  var isSelected = i18n.language === languageStr;
                  return React.createElement("div", {
                              className: "language-selector__language " + (
                                isSelected ? "language-selector__language--selected" : ""
                              ),
                              onClick: (function (param) {
                                  return Command$Web.send({
                                              TAG: /* ChangeLanguage */4,
                                              _0: language
                                            });
                                })
                            }, Curry._2(t1, "LANGUAGE." + languageStr.toUpperCase(), {
                                  lng: languageStr
                                }));
                }));
}

var make = LanguageSelector;

export {
  make ,
  
}
/*  Not a pure module */
