// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import ProgressBarCss from "./ProgressBar.css";

function clamp(value, min, max) {
  if (Caml_obj.caml_lessthan(value, min)) {
    return min;
  } else if (Caml_obj.caml_greaterthan(value, max)) {
    return max;
  } else {
    return value;
  }
}

function ProgressBar(Props) {
  var minOpt = Props.min;
  var maxOpt = Props.max;
  var value = Props.value;
  var min = minOpt !== undefined ? minOpt : 0.0;
  var max = maxOpt !== undefined ? maxOpt : 100.0;
  var width = (value - min) / (max - min) * 100.0;
  var width$1 = clamp(width, 0.0, 100.0);
  return React.createElement("div", {
              className: "progress-bar"
            }, React.createElement("div", {
                  className: "progress-bar__background"
                }), React.createElement("div", {
                  className: "progress-bar__foreground",
                  style: {
                    width: "" + width$1 + "%"
                  }
                }));
}

var make = ProgressBar;

export {
  make ,
  
}
/*  Not a pure module */
