// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Electron from "electron";

var resourcesPath = Electron.app.isPackaged ? Path.join(process.resourcesPath) : Path.join(__dirname, "..", "resources");

var imgPath = Path.join(resourcesPath, "img");

var scriptsPath = Path.join(resourcesPath, "scripts");

var webPath = Electron.app.isPackaged ? Path.join(resourcesPath, "web", "index.html") : "http://localhost:3000";

export {
  resourcesPath ,
  imgPath ,
  scriptsPath ,
  webPath ,
  
}
/* resourcesPath Not a pure module */
